// Generated by Wrangler on Tue Aug 27 2024 01:12:06 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	NODE_ENV: "production";
	SESSION_SECRET: string;
	DB: D1Database;
	DB_TEST: D1Database;
}
