// Generated by Wrangler on Mon Aug 26 2024 23:47:03 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	NODE_ENV: "production";
	SESSION_SECRET: string;
	DB: D1Database;
}
