// Generated by Wrangler on Tue Aug 27 2024 00:36:57 GMT+0200 (Mitteleuropäische Sommerzeit)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	NODE_ENV: string;
	DB: D1Database;
}
